[package]
name = "intric8"
version = "0.1.0"
authors = ["Th0rgal <thomas.marchand@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.x25519-dalek]
version = "^0.5"