[package]
name = "intric8"
version = "0.1.0"
authors = ["Th0rgal <thomas.marchand@tuta.io>"]
edition = "2018"

[dependencies]
x25519-dalek = "^0.5"
rand_os = "0.1"
base64 = "0.11.0"

[profile.release]
lto = true